import { ITyroUiNavbarMenuCategory } from '../interface/ityro-ui-navbar-menu-category';
import { ITyroUiNavbarMenuItem } from '../interface/ityro-ui-navbar-menu-item';

export const NavbarMenuPinned: ITyroUiNavbarMenuItem = {
  name: 'Tyrolium',
  description: 'Maison mère',
  descriptionEn: 'Parent company',
  image: 'assets/tyrolium-ui/projects/Tyrolium.png',
  link: 'https://tyrolium.fr',
};

export const NavbarMenuCategory: ITyroUiNavbarMenuCategory[] = [
  {
    label: 'Filiales',
    labelEn: 'Subsidiaries',
    open: true,
    items: [
      {
        name: 'TyroServ',
        description: 'Serveur Minecraft',
        descriptionEn: 'Minecraft Server',
        image: 'assets/tyrolium-ui/projects/TyroServ.png',
        link: 'https://tyroserv.fr',
      },
      {
        name: 'SolidServ',
        description: 'Hébergeur de serveurs',
        descriptionEn: 'Server hosting',
        image: 'assets/tyrolium-ui/projects/SolidServ.png',
        link: 'https://solidserv.fr',
      },
      {
        name: 'Influnias',
        description: "Agence d'influenceurs",
        descriptionEn: 'Influencer agency',
        image: 'assets/tyrolium-ui/projects/Influnias.png',
        link: 'https://influnias.fr',
        subOpen: false,
        subItems: [
          {
            name: 'Vturias',
            description: 'Agence de VTubers',
            descriptionEn: 'VTuber agency',
            image: 'assets/tyrolium-ui/projects/Vturias.png',
            link: 'https://vturias.fr',
            isSubItem: true,
          },
        ],
      },
      {
        name: 'TyroCiel',
        description: 'Studio de jeu-vidéo',
        descriptionEn: 'Video game studio',
        image: 'assets/tyrolium-ui/projects/TyroCiel.png',
        imageLight: 'assets/tyrolium-ui/projects/TyroCiel-White.png',
        link: 'https://tyrociel.fr',
      },
      {
        name: 'Gamenium',
        description: "Site d'actu jeu-vidéo",
        descriptionEn: 'Gaming news site',
        image: 'assets/tyrolium-ui/projects/Gamenium.png',
        link: 'https://gamenium.fr',
      },
      {
        name: 'NexiumiaCRM',
        description: 'CRM',
        descriptionEn: 'CRM',
        image: 'assets/tyrolium-ui/projects/NexiumiaCRM.png',
        link: 'https://nexiumiacrm.fr',
      },
      {
        name: 'Useritium',
        description: 'Compte',
        descriptionEn: 'Account',
        image: 'assets/tyrolium-ui/projects/Useritium.png',
        link: 'https://useritium.fr',
      },
    ],
  },
  {
    label: 'Corporate',
    labelEn: 'Corporate',
    open: false,
    items: [
      {
        name: 'RSE',
        nameEn: 'CSR',
        description: 'Responsabilité sociétale',
        descriptionEn: 'Corporate social responsibility',
        icon: 'ri-leaf-fill',
        link: '/rse',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Partenaires',
        nameEn: 'Partners',
        description: 'Nos partenaires',
        descriptionEn: 'Our partners',
        icon: 'ri-group-fill',
        link: '/partenaires',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Recrutements',
        nameEn: 'Jobs',
        description: "Offre d'emploi",
        descriptionEn: 'Job offers',
        icon: 'ri-briefcase-fill',
        link: 'https://jobs.tyrolium.fr',
      },
      {
        name: 'Tyrolium Labs',
        description: "Laboratoire d'innovation",
        descriptionEn: 'Innovation lab',
        icon: 'ri-flask-fill',
        link: '/labs',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Chronologie',
        nameEn: 'Timeline',
        description: 'Notre histoire',
        descriptionEn: 'Our history',
        icon: 'ri-time-fill',
        link: '/chronologie',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Équipe',
        nameEn: 'Team',
        description: 'Qui sommes-nous',
        descriptionEn: 'Who we are',
        icon: 'ri-group-fill',
        link: '/equipe',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Media Kit',
        description: 'Charte graphique',
        descriptionEn: 'Brand guidelines',
        icon: 'ri-palette-fill',
        link: '/mediakit',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Boutique',
        nameEn: 'Shop',
        description: "Goodies aux couleurs de l'entreprise",
        descriptionEn: 'Company merchandise',
        icon: 'ri-store-fill',
        link: 'https://tyrolium-shop.myspreadshop.fr/',
      },
    ],
  },
  {
    label: 'Service & Info',
    labelEn: 'Service & Info',
    open: false,
    items: [
      {
        name: 'Contactez-nous',
        nameEn: 'Contact',
        description: 'Formulaire de contact',
        descriptionEn: 'Contact form',
        icon: 'ri-mail-fill',
        link: '/contact',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Serveurs',
        nameEn: 'Servers',
        description: 'Liste des serveurs',
        descriptionEn: 'Server list',
        icon: 'ri-server-fill',
        link: '/server',
        host: 'https://tyrolium.fr',
      },
      {
        name: 'Uptime Robot',
        description: 'État des serveurs',
        descriptionEn: 'Server status',
        icon: 'ri-pulse-fill',
        link: 'https://stats.uptimerobot.com/7z9o3SEnWX',
      },
      {
        name: 'Légal',
        nameEn: 'Legal',
        description: 'Mentions légales',
        descriptionEn: 'Legal notice',
        icon: 'ri-scales-fill',
        link: '/legal',
        host: 'https://tyrolium.fr',
        subOpen: false,
        subItems: [
          {
            name: 'CGU',
            nameEn: 'ToS',
            description: "Contrat général d'utilisation",
            descriptionEn: 'Terms of Service',
            icon: 'ri-file-user-fill',
            link: '/legal/cgu',
            host: 'https://tyrolium.fr',
            isSubItem: true,
          },
          {
            name: 'CGV',
            nameEn: 'Terms of Sale',
            description: 'Contrat général de vente',
            descriptionEn: 'Terms of Sale',
            icon: 'ri-file-list-3-fill',
            link: '/legal/cgv',
            host: 'https://tyrolium.fr',
            isSubItem: true,
          },
        ],
      },
    ],
  },
  {
    label: 'Interne',
    labelEn: 'Internal',
    open: false,
    items: [
      {
        name: 'ERP',
        description: "Gestion d'entreprise",
        descriptionEn: 'Business management',
        icon: 'ri-building-2-fill',
        link: 'https://app.tyrolium.fr',
      },
      {
        name: 'Repo',
        description: 'Serveur de Repository',
        descriptionEn: 'Repository server',
        icon: 'ri-git-repository-fill',
        link: 'http://repo.tyrolium.fr',
      },
    ],
  },
];
